[package]
name = "ojs-diesel-example"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
ojs = { version = "0.5.0", features = ["reqwest-transport"] }
ojs-diesel = { version = "0.5.0", path = ".." }
diesel = { version = ">=2.3.12, <2.4", features = ["postgres"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"
